---
title: "estimation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EM
A few words about the estimation. 
For the ease of the things here I assume that the data frame has already been splitted at the change points of the frailty, to be determined a priori. 

So I have the following notation: let the $L$ unique event time points be $t_1 ... t_L$, and the $K$ split points of the frailty $0 = \tau_1 ... \tau_K = t_L$. I assume $K \leq L$. At most, if $K = L$, then the $\tau$ vector is identical to the $t$ vector. 

Now let's work in cluster $i$, which shared the same frailty process. To cover a wide range of situations I assume that $j$ is a process within cluster $i$. If we are talking Andersen-Gill recurrent events, then $j = 1$. So for each $(i,j)$ pair there will be a bunch of observations. They are in between the $\tau$ points or the $t$ points. 

Assume that there is no left truncation. Then an observation $(i,j,k)$ starts at the previous $\tau$ and ends either at the next $\tau$ or the next $t$, whichever comes first. Note that this observation might contain several event time points. 

Let's make a mapping then!
At $t_k$ we have $\tau_{l(k)}$. And each $l$ is common to several $k$'s. Refer as $t_{k(l)}$ as the "inverse" in this case. 

## log-likelihood
Now to work on cluster $i$, we have the following log-likelihood (I ommitt $i$):
$$
\prod_j 
$$
