// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Estep_id
NumericVector Estep_id(NumericVector events, NumericVector cvec, double aalpha, double ggamma, int dist, double pvfm, NumericVector times, double llambda);
RcppExport SEXP dynfrail_Estep_id(SEXP eventsSEXP, SEXP cvecSEXP, SEXP aalphaSEXP, SEXP ggammaSEXP, SEXP distSEXP, SEXP pvfmSEXP, SEXP timesSEXP, SEXP llambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cvec(cvecSEXP);
    Rcpp::traits::input_parameter< double >::type aalpha(aalphaSEXP);
    Rcpp::traits::input_parameter< double >::type ggamma(ggammaSEXP);
    Rcpp::traits::input_parameter< int >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type pvfm(pvfmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< double >::type llambda(llambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(Estep_id(events, cvec, aalpha, ggamma, dist, pvfm, times, llambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"dynfrail_Estep_id", (DL_FUNC) &dynfrail_Estep_id, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynfrail(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
