# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Estep_id <- function(events, cvec, aalpha, ggamma, dist, pvfm, times, llambda) {
    .Call(`_dynfrail_Estep_id`, events, cvec, aalpha, ggamma, dist, pvfm, times, llambda)
}

Vcov_adj <- function(events_l, cvec_l, aalpha, ggamma, dist, pvfm, times_l, llambda, elp_l, xelph_l, tau_l, interval_rows_l, ez_l, n_times, n_covs) {
    .Call(`_dynfrail_Vcov_adj`, events_l, cvec_l, aalpha, ggamma, dist, pvfm, times_l, llambda, elp_l, xelph_l, tau_l, interval_rows_l, ez_l, n_times, n_covs)
}

